Production
andela-oduyile/Inverted-Index-App pull request #12
Opened 2017-03-17 18:32 UTC by andela-oduyile

2017-03-20 09:36 UTC, ngozi-ekekwe requested changes

2017-03-20 09:36 UTC, andela-nekekwe commented on .codeclimate.yml
> +      - ruby
You just need to include only javascript alone, remove other languages

2017-03-20 09:36 UTC, andela-nekekwe commented on .codeclimate.yml
> +  - "**.jsx"
same here, remove extensions that are not required.

2017-03-20 09:36 UTC, andela-nekekwe commented on public/js/invertedindexutil.js
> +  static Tokenize(text) {
The 't' in Tokenize method should be in lowercase

2017-03-22 10:46 UTC, andela-oduyile commented on .codeclimate.yml
> +      - ruby
Done

2017-03-22 10:46 UTC, andela-oduyile commented on .codeclimate.yml
> +  - "**.jsx"
Done

2017-03-24 09:18 UTC, ngozi-ekekwe approved these changes
Looks Good

2018-07-02 15:07 UTC, closed without merging